### PR TITLE
added events

### PR DESCRIPTION
**Pull request by abhijeetmanhas**
@ArshitaKalra suggested changes? should cards be more broader or color scheme or padding related if any?
Screenshot from 2019-12-26 03-59-14

### CODE REVIEW

**Comment by ArshitaKalra** [comment]
Add space between rows of images.

**Comment by abhijeetmanhas** [comment]
ok

**Comment by abhijeetmanhas** [comment]
https://abhijeetmanhas.github.io/AstraX/ @ArshitaKalra done. Review it once

**Comment by shreyasbapat** [comment]
Event names must always be visible

_______________________________________
This email is sent from a smartphone. Please ignore grammatical mistakes
and typographical errors.
_______________________________________

**Comment by abhijeetmanhas** [comment]
Only event name , not description, right?

**Pull request merged**
